package Lab1Tp6.vistas;
import Lab1Tp6.entidades.Producto;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class ConsultaPrecio extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    
    
    public ConsultaPrecio() {
        initComponents();
        armarCabecera();
    }

    private void armarCabecera() {
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        jtblProductos.setModel(modelo);
    }
    
    private void borrarFilas() {
        while (modelo.getRowCount() != 0) {
            modelo.removeRow(0);
        }
    }
    
   private String[] crearFila(Producto p) {
        String[] fila = new String[modelo.getColumnCount()];
        
        fila[0] = String.valueOf(p.getCodigo());
        fila[1] = p.getDescripcion();
        fila[2] = String.valueOf(p.getPrecio());
        fila[3] = String.valueOf(p.getStock());
        
        return fila;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProductos = new javax.swing.JTable();
        jtfPrecioMinimo = new javax.swing.JTextField();
        jtfPrecioMaximo = new javax.swing.JTextField();

        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BUSCAR POR PRECIO");

        jLabel2.setText("Entre $");

        jLabel3.setText("y");

        jtblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblProductos);

        jtfPrecioMinimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPrecioMinimoKeyReleased(evt);
            }
        });

        jtfPrecioMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPrecioMaximoActionPerformed(evt);
            }
        });
        jtfPrecioMaximo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPrecioMaximoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPrecioMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfPrecioMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jtfPrecioMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfPrecioMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPrecioMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPrecioMaximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrecioMaximoActionPerformed

        private boolean ValidacionDoubles(JTextField tx) {

        try {
            Double.parseDouble(tx.getText());
        }
        catch (Exception e) {
            return false;
        }

        return true;

    }
    
    
    private void jtfPrecioMinimoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecioMinimoKeyReleased
        // TODO add your handling code here:
        borrarFilas();
        if (ValidacionDoubles(jtfPrecioMinimo) && ValidacionDoubles(jtfPrecioMaximo)) {
            double menor = Double.parseDouble(jtfPrecioMinimo.getText());
            double mayor = Double.parseDouble(jtfPrecioMaximo.getText());
            
            for (Producto p : Menu.getProductos()) {
                if (p.getPrecio() >= menor && p.getPrecio() <= mayor) {
                    modelo.addRow(crearFila(p));
                }
            }
        }
    }//GEN-LAST:event_jtfPrecioMinimoKeyReleased

    private void jtfPrecioMaximoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecioMaximoKeyReleased
        // TODO add your handling code here:
        borrarFilas();
        if (ValidacionDoubles(jtfPrecioMinimo) && ValidacionDoubles(jtfPrecioMaximo)) {
            double menor = Double.parseDouble(jtfPrecioMinimo.getText());
            double mayor = Double.parseDouble(jtfPrecioMaximo.getText());
            
            for (Producto p : Menu.getProductos()) {
                if (p.getPrecio() >= menor && p.getPrecio() <= mayor) {
                    modelo.addRow(crearFila(p));
                }
            }
        }
    }//GEN-LAST:event_jtfPrecioMaximoKeyReleased

    

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblProductos;
    private javax.swing.JTextField jtfPrecioMaximo;
    private javax.swing.JTextField jtfPrecioMinimo;
    // End of variables declaration//GEN-END:variables
}
