package Lab1Tp6.vistas;

import Lab1Tp6.entidades.Producto;
import javax.swing.table.DefaultTableModel;

public class ConsultaNombre extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    
    public ConsultaNombre() {
        initComponents();
        armarCabecera();
    }

    private void armarCabecera() {
        modelo.addColumn("Código");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        jtListadoPorNombre.setModel(modelo);
    }
    
    private void borrarFilas() {
        while (modelo.getRowCount() != 0) {
            modelo.removeRow(0);
        }
    }
    
    private String[] crearFila(Producto p) {
        String[] fila = new String[modelo.getColumnCount()];
        
        fila[0] = String.valueOf(p.getCodigo());
        fila[1] = p.getDescripcion();
        fila[2] = String.valueOf(p.getPrecio());
        fila[3] = String.valueOf(p.getStock());
        
        return fila;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlListadoPorNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListadoPorNombre = new javax.swing.JTable();
        jlCaracteres = new javax.swing.JLabel();
        jtCaracteres = new javax.swing.JTextField();

        setResizable(true);

        jlListadoPorNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlListadoPorNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlListadoPorNombre.setText("Listado por Nombre");

        jtListadoPorNombre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListadoPorNombre.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jtListadoPorNombre);

        jlCaracteres.setText("Escriba los primeros caracteres");

        jtCaracteres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtCaracteresKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCaracteres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCaracteres))
                    .addComponent(jlListadoPorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlListadoPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtCaracteres)
                    .addComponent(jlCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCaracteresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCaracteresKeyReleased
        borrarFilas();
        String jtext = jtCaracteres.getText().toLowerCase();

        if (jtext.equals("")) {
            borrarFilas();
        } else {
            for (Producto p : Menu.getProductos()) {
                if (p.getDescripcion().toLowerCase().startsWith(jtext)) {
                    modelo.addRow(crearFila(p));
                }
            }
        }
    }//GEN-LAST:event_jtCaracteresKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlCaracteres;
    private javax.swing.JLabel jlListadoPorNombre;
    private javax.swing.JTextField jtCaracteres;
    private javax.swing.JTable jtListadoPorNombre;
    // End of variables declaration//GEN-END:variables
}
